# Generated by Django 4.1.5 on 2023-02-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aricle',
            new_name='article',
        ),
    ]
